### PR TITLE
add support for different lipids

### PR DESCRIPTION
**Pull request by HubLot**
Currently:
 - Berger DOPC
 - Berger POPS
 - Berger DPPC
 - GROMOS-CPK POPC
 - GROMOS-CPK POPS
 - GROMOS 53A6L DPPC

It's in draft mode while I add more lipids but it will help tracking the new lipids added

### CODE REVIEW

**Comment by HubLot** [comment]
can be merged now

**Comment by patrickfuchs** [comment]
Great work, thanks @HubLot ! I quickly went through the files and for me it's OK, except the file names for GROMOS-CKP: could you rename CPK to CKP?

**Comment by patrickfuchs** [comment]
Could you please also tell the lipids you added in CHANGELOG.md?

**Comment by HubLot** [comment]
okay done!

**Pull request merged**
