### PR TITLE
Expend tests for Python 3.6 

### LINKED ISSUE #30: Expand tests down to Python 3.6
BuildH should work with Python 3.6. We should perform tests also with this version.

### PR DESCRIPTION
**Pull request by HubLot**
close #30

### CODE REVIEW

**Comment by pierrepo** [comment]
@HubLot it seems Python >= 3.7 is required... but why :astonished: ?

**Comment by HubLot** [comment]
Yeah.. Looks like it's due to MDAnalysis but I can install it on a Python 3.6 on my laptop...

**Comment by pierrepo** [comment]
>Yeah.. Looks like it's due to MDAnalysis but I can install it on a Python 3.6 on my laptop...

Same here in a conda env.

>Edit: no, in fact it seems it due to a too recent version of pip...

:scream:

**Comment by HubLot** [comment]
Ok, I don't understand the error in the CI.

When I use "pip install -r requirements.txt" it fails on Python 3.6 but when I use "pip install numpy pandas MDAnalysis" it works on Python 3.6...

**Comment by pierrepo** [comment]
This weird. 
As a workaround, can you make a special case when  python-version == 3.6 and install numpy pandas and mdanalysis in the command line? The general case (for python 3.7 and 3.8) will be with the requirements.txt file.

**Comment by HubLot** [comment]
In fact, when using the *requirements.txt*, it tried to install numpy-1.20.0rc1 which only support Python >= 3.7...

> As a workaround, can you make a special case when python-version == 3.6 and install numpy pandas and mdanalysis in the command line? The general case (for python 3.7 and 3.8) will be with the requirements.txt file.
Good idea, I'll try.

**Comment by pierrepo** [comment]
@HubLot 
Can you "print" the version of Python and pip in the action? I guess something like this:
```
      run: |
        python --version
        python -m pip --version
        python -m pip install --upgrade pip
        python -m pip --version
        pip install pytest
        pip install MDAnalysis
        pip install -r requirements.txt
```

**Comment by HubLot** [comment]
You have it in the logs : https://github.com/patrickfuchs/buildH/runs/1594122777

**Comment by pierrepo** [comment]
Something worth trying: 

- invert package order in requirements.txt (first MDAnanalysis)
- remove numpy in requirements.txt as it's aleady a dependency of MDAnalysis

**Comment by pierrepo** [comment]
Whoooooooooooooo :champagne:

**Comment by HubLot** [comment]
> Something worth trying:
> 
>     * invert package order in requirements.txt (first MDAnanalysis)
> 
>     * remove numpy in requirements.txt as it's aleady a dependency of MDAnalysis

same...

It's very weird because even if MDAnalysis is listed at the end  (`pip install numpy pandas MDAnalysis`), pip try to install first and it failed.
If I split the command in 2, it install correctly numpy 1.19 and then MDAnalysis...

So, I made a test for the Python version and install the modules accordingly.

**Comment by HubLot** [comment]
It can be merged now!

Thanks @pierrepo  for this great issue :D

**Comment by pierrepo** [comment]
You're welcome. This PR was a nightmare... :scream: 
I will merge this PR.

**Pull request merged**
