### PR TITLE
Write only one output file.

### PR DESCRIPTION
**Pull request by HubLot**
As discussed previously, I modified the code to write only one output file with J. Melcr's style. The other style (A. Pineiro) has been renamed as *alternate*.
I kept the origin of the style in the docstrings of the functions.

I also modified the "-o" argument to accept whole filename (and not just basename). This will allow users to choose the full name of their output files.

### CODE REVIEW

**Review by patrickfuchs — COMMENTED** [review]
To me it's fine, but there seems to be a conflict in `test_core.py`, could you have a look? I'm not sure waht to do and don't want to destroy everything 😉

**Comment by HubLot** [comment]
Sure, it's due to the previous merge with #37 
I'll rebase this branch with the current master and it should be ok.

**Comment by HubLot** [comment]
good to merge!

**Comment by patrickfuchs** [comment]
Thanks! I merge now this PR, without having the review of @pierrepo,  since it's more convenient for @HubLot 's next PR [privat communication] 😉

**Pull request merged**
