### PR TITLE
Fix python version for readthedocs

### PR DESCRIPTION
**Pull request by pierrepo**

### CODE REVIEW

**Comment by pierrepo** [comment]
Hello @patrickfuchs and @HubLot 

The doc should compile now:
https://readthedocs.org/projects/buildh/builds/14183663/

I had to lock the Python version in the `binder/environment.yml` file. Tests to build doc are now running only for the Python version provided in `binder/environment.yml` (i.e. 3.8).

**Review by HubLot — APPROVED** [review]
Well done!
I think having only one version of python for the build-doc test is much better

**Comment by pierrepo** [comment]
Indeed. And it consumes less resources.

**Review by patrickfuchs — APPROVED** [review]
Excellent, thanks @pierrepo 👍

**Pull request merged**
