### PR TITLE
Add logo in left menu header

### LINKED ISSUE #108: buildH logo
Here's a first try for **buildH** logo. 

buildH

What do you think?

### PR DESCRIPTION
**Pull request by pierrepo**
Fix #108

### CODE REVIEW

**Comment by pierrepo** [comment]
I added the logo in the upper left corner:
image

Do we also keep the logo in the middle?

**Comment by patrickfuchs** [comment]
Maybe not? I find it redundant.

**Comment by pierrepo** [comment]
Would you prefer something like this?

image

**Comment by HubLot** [comment]
It may be redundant on the home page but that's all. I don't mind having it at both places.

**Comment by patrickfuchs** [comment]
Now I'm hesitating... What do you think @pierrepo ?

**Comment by pierrepo** [comment]
I would keep it only in the sidebar. But we trust you for the final decision :smile:

**Comment by patrickfuchs** [comment]
Always follow your first impression, so I would keep it like that only in the side bar 👍 Let me know when I can merge

**Comment by pierrepo** [comment]
Here you are @patrickfuchs, no more logo in the main page.

**Comment by pierrepo** [comment]
@patrickfuchs you can review this PR and merge it if you like it.

**Review by patrickfuchs — APPROVED** [review]

**Pull request merged**
