### PR TITLE
Archive repository to Software Heritage

### LINKED ISSUE #128: Automate archiving in Software Heritage upon release
Software Heritage Save action
https://github.com/marketplace/actions/save-to-software-heritage

### PR DESCRIPTION
**Pull request by pierrepo**
On release only.

Fix #128

### CODE REVIEW

**Comment by patrickfuchs** [comment]
All the commits we pushed yesterday on the master branch appear again here, is there a reason?

**Comment by HubLot** [comment]
arf indeed :( a rebase on the master is still possible?

**Comment by pierrepo** [comment]
I already did a rebase :thinking:

**Comment by HubLot** [comment]
i guess something went wrong :s
You could rewrite the history of the branch with git rebase -i, remove the useless commit and squash the 2 needed into 1 :)

**Comment by pierrepo** [comment]
Sorry. I'm unable to do this. Could you have a look? Or should I delete the branch?

**Comment by HubLot** [comment]
okay, i look at it

**Comment by HubLot** [comment]
Okay, I think I fix it. could you verify @pierrepo ?

**Comment by pierrepo** [comment]
This looks very good :star_struck: Thanks @HubLot

**Comment by pierrepo** [comment]
@patrickfuchs you can merge.

**Pull request merged**
