### PR TITLE
[WIP] Create Python package

### PR DESCRIPTION
**Pull request by pierrepo**
Here is an attempt to create a Python package for Pypi.

To test this PR, you can:

1. Clone this fork:
```
$ https://github.com/pierrepo/buildH.git buildh-tmp
$ cd buildh-tmp
$ git checkout create-package
```

2. Build and load conda environment:
```
$ conda env create -f binder/environment.yml
$ conda activate buildh
```

3. Install buildH in the conda env:
```
$ pip install -e .
```

4. Run buildH
```
$ buildH
```

@HubLot could you check relative imports (`from . import toto`) are correct?

Tests are expected to fail.

### CODE REVIEW

**Comment by pierrepo** [comment]
And tests passed! :tada:

**Comment by pierrepo** [comment]
You can even try with Binder: 

https://mybinder.org/v2/gh/pierrepo/buildH/create-package?urlpath=lab

**Review by patrickfuchs — APPROVED** [review]
Everything seems fine to me.

**Review by HubLot — COMMENTED** [review]
Thanks for the PR. It's great.
I just have one comment: I would put all functions from the new `__init__.py` to a new dedicated file (called *script.py* or *cli.py*) to handle the entry point. This would better separate the code. Plus, if we let those fonctions in `__init__.py` they will be accessible when a user import buildh (example : `import buildh; buildh.isfile()`). Usually, I tend to have a very minimal `__init__.py` file with only import to be exposed and general setup (like a logger).

About the tests, usually I put the *tests* directory inside the module but it seems both layouts are discussed and debated (https://docs.pytest.org/en/reorganize-docs/new-docs/user/directory_structure.html).

**Comment by pierrepo** [comment]
OK. I can create a `cli.py` file that will contain the script entry point.

**Comment by pierrepo** [comment]
@HubLot This should be fine now. Could you have a look?

**Review by HubLot — APPROVED** [review]
Perfect!

**Comment by pierrepo** [comment]
Thanks @HubLot 

@patrickfuchs could you please merge this PR?

**Comment by HubLot** [comment]
@pierrepo, it seems there are duplicated commits :s

**Comment by pierrepo** [comment]
Yes... I tried rebase... I shouldn't have.

**Comment by pierrepo** [comment]
Do you have an idea how to clean the mess of the duplicated commits? (Not in a cherry-picking mood though).

**Comment by HubLot** [comment]
Well, I think the best here is to revert to the last good commit (5f98786) and force push it I guess. This should remove the others.

The PR will not be up-to-date compared to master but it's not a big deal since it's just one commit on different files.

**Comment by pierrepo** [comment]
Thanks @HubLot 
This look better.

**Comment by pierrepo** [comment]
@patrickfuchs you can now merge :wink:

**Pull request merged**
