### PR TITLE
Add various minor improvements

### PR DESCRIPTION
**Pull request by HubLot**
This PR regroup various small modifications to the code:

- Change the flag for the lipid topology from `-tl` to `-lt` (69f17b6)
- Transform the `UserWarning` exception in `main` into `sys.exit()` (e7b8db6)
- Improve handling of raised exceptions across code (a909f3b)
- Add a check function to verify the consistency of the def file and the topology one (make sure all atoms of the first is present in the 2nd and make sure all hydrogens attached to a carbon are present in the firs one) (311bd28)
- Create a new module `utils.py` to regroup the different check functions. If we gonna create a second entry point, some of theses functions will be re-used, so it's better to have them in a module seperated from the `cli` one. (1f11072)
- I realize some of those check functions were very slow due to the many calls of `select_atoms()`. I improved them to be much faster using `set()` structure. (fd6fd69)

### CODE REVIEW

**Comment by patrickfuchs** [comment]
Looks great, thanks @HubLot! I only saw one typo, I think. I was wondering, maybe you can add to this miscellaneous PR  - as we discussed - the implementation of the `-c` /  `--coor` option And also change the name `topfile               Topology file` to `coorfile               Coordinate file` with `-h` option?

**Comment by HubLot** [comment]
I planed to do it on another PR but i cant put it here.
In both cases, some README and launch should be updated too.

**Comment by HubLot** [comment]
In fact, it didn't require big modifications so I updated the options in this PR with the last commit.

**Comment by patrickfuchs** [comment]
Indeed, it's great like that 👍. Let's go for the merge 😄 !

**Pull request merged**
