### PR TITLE
Numba Optimization

### PR DESCRIPTION
**Pull request by HubLot**
Here, the PR to support Numba optimizations for the `geometry` module.

The modifications are quite simple and decrease the compute time of more than 50% (for the test case bilayer of 128POPC Berger with 25 frames) : from ~18s to ~7.5s

In the other hand, since Numba use its own routines for some operations and coordinates are in `np.float32` (due to MDAnalysis), it changes a bit the results (start at 5th decimals) (see some explanations [here](https://stackoverflow.com/questions/54262281/using-numbas-jit-causing-math-inconsistencies-with-numpys-float32-being-used)). 
Hence, the references values of some tests had to be updated.

For the reference bilayer (in `docs/Berger_POPC_test_case/`), the OP results are the same than previous. (Only the value of `OP_stddev`  of `gamma3_1` has changed from 0.40509 to 0.40510 **only** when using the PDB alone.

But before merging, I would like to see the results are still consistent on a bigger trajectory (few thousands frames for example), @patrickfuchs could you test ?

### CODE REVIEW

**Comment by patrickfuchs** [comment]
Yeah, very great PR, thanks a lot @HubLot 😎 !!! I will try it this afternoon on a real traj of 2500 frames.

**Comment by patrickfuchs** [comment]
Here are the results of my tests on a traj of 2500 frames (128 popc) :

```
try_Jan2021_wo_Numba/TIME:real    35m51.711s
try_Apr2021_wo_Numba/TIME:real    28m30.202s
try_Apr2021_w_Numba/TIME:real    7m17.686s
try2_Apr2021_w_Numba/TIME:real    7m16.338s
```

Wooooo, Numba rocks 🚀 !!! You can see that some other optimizations went on between January and April 2021 😉

**Comment by patrickfuchs** [comment]
I realize the gain is more than doubled!!! In fact, the higher the number of frames, the higher the gain!!! 
So if you are ok, I'm ready for the merge.

**Comment by pierrepo** [comment]
Amazing perf!

**Comment by HubLot** [comment]
That's really great!
The OP results are still consistent compared without Numba ?

**Comment by patrickfuchs** [comment]
>The OP results are still consistent compared without Numba ?

Yes, I did a diff, they are strictly identical up to the 5th digit!!!

**Comment by patrickfuchs** [comment]
Just did another try on this traj: https://zenodo.org/record/2641987 (4500 frames with 144 POPE lipids)
wNumba ~ 15'
woNumba ~ 51'

**Comment by pierrepo** [comment]
@patrickfuchs could you keep these numbers somewhere? That could be usefull for the paper.

**Comment by patrickfuchs** [comment]
Sure 👍 !

**Pull request merged**
