### PR TITLE
Simplify CH reconstruction

### PR DESCRIPTION
**Pull request by patrickfuchs**
Following the discussion of issue #88, here's the simplification of CH reconstruction. After a verification on POPC and cholesterol, the difference in H coodinates  between the old way (as implemented by Jon Kapla) and the new proposed way is systematically below 1e-5. Because the 6th or 7th may be affected, it makes the tests fail. @HubLot is OK to fix those tests.

### CODE REVIEW

**Comment by HubLot** [comment]
It's weird because when I checked the OP_buildH.out (for just the `start_128popc.pdb`) between the 2 versions, I found quite differences :

Original :
```
g2_1                 POPC    C13   H131  -0.10922  0.36155  0.03196
```

New:
```
g2_1                 POPC    C13   H131  -0.13552  0.34554  0.03054
```

The test fails also with significant differences. For example with `test_get_CH()` :

```
E        value: array([26.542433, 44.169685, 25.546448], dtype=float32)
E        ref:   array([26.61869, 44.14296, 25.55245], dtype=float32)
```

I know we checked this morning the reconstruction so I don't explain it :D

**Comment by patrickfuchs** [comment]
Found the problem 😅 ! When I created the branch this morning, I forgot to normalize the vectors when calculating v2...! 

```
v2 = (helper1-atom) + (helper2-atom) + (helper3-atom)
```
Because some bonds have not exactly the same length, `v2` was not exactly along the median. With this fix it works now:

```
v2 = geo.normalize(helper1-atom) + geo.normalize(helper2-atom) + geo.normalize(helper3-atom)
```
Checking the OP:

```
$ grep g2_1 OP_buildH_*
OP_buildH_new_CH.out:g2_1                 POPC    C13   H131  -0.10922  0.36155  0.03196
OP_buildH_old_CH.out:g2_1                 POPC    C13   H131  -0.10922  0.36155  0.03196
```

The PDB are also strictly identical. Checking the diff manually, I found values < 1e-5.

**Comment by HubLot** [comment]
good catch!

**Comment by patrickfuchs** [comment]
This PR shoud fix issue #88.

**Comment by patrickfuchs** [comment]
@HubLot , do you think it's OK for the merge?

**Comment by HubLot** [comment]
yes!

**Pull request merged**
